// TESTDATEN: keine echten FKK-Orte. Sie liegen rund um Celle, damit die App sofort testbar ist.
const places=[
{id:1,name:"Teststrand Celle Nord",lat:52.664,lon:10.080,description:"TESTDATEN – kein realer FKK-Strand.",type:"Test"},
{id:2,name:"Teststrand Celle Süd",lat:52.570,lon:10.050,description:"TESTDATEN – kein realer FKK-Strand.",type:"Test"},
{id:3,name:"Teststrand Celle West",lat:52.610,lon:9.970,description:"TESTDATEN – kein realer FKK-Strand.",type:"Test"}];
let userLocation=null,map,userMarker,radiusCircle,markers=[];
const radius=document.getElementById("radius"),radiusValue=document.getElementById("radiusValue"),status=document.getElementById("status"),list=document.getElementById("places"),count=document.getElementById("resultCount");
function dist(a,b,c,d){const R=6371,r=Math.PI/180,x=(c-a)*r,y=(d-b)*r,z=Math.sin(x/2)**2+Math.cos(a*r)*Math.cos(c*r)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function results(){if(!userLocation)return places.map(p=>({...p,distance:null}));const r=+radius.value;return places.map(p=>({...p,distance:dist(userLocation.lat,userLocation.lon,p.lat,p.lon)})).filter(p=>p.distance<=r).sort((a,b)=>a.distance-b.distance)}
function render(){markers.forEach(m=>map.removeLayer(m));markers=[];const rs=results();count.textContent=`(${rs.length} angezeigt)`;if(userLocation){if(radiusCircle)map.removeLayer(radiusCircle);radiusCircle=L.circle([userLocation.lat,userLocation.lon],{radius:+radius.value*1000,color:"#0f766e",fillOpacity:.1}).addTo(map)}rs.forEach(p=>{const m=L.marker([p.lat,p.lon]).addTo(map).bindPopup(`<b>🏖️ ${esc(p.name)}</b>`);m.on("click",()=>show(p));markers.push(m)});list.innerHTML=rs.map(p=>`<article class="place"><h3>🏖️ ${esc(p.name)}</h3><p class="distance">${p.distance==null?"Testpunkt – Standort noch nicht freigegeben":p.distance.toFixed(1)+" km entfernt"}</p><p>${esc(p.description)}</p><button onclick="showById(${p.id})">Details</button></article>`).join("")}
function locate(){if(!navigator.geolocation){status.textContent="Standort wird nicht unterstützt.";return}status.textContent="Standort wird ermittelt …";navigator.geolocation.getCurrentPosition(p=>{userLocation={lat:p.coords.latitude,lon:p.coords.longitude};if(userMarker)map.removeLayer(userMarker);userMarker=L.marker([userLocation.lat,userLocation.lon]).addTo(map).bindPopup("📍 Dein Standort");map.setView([userLocation.lat,userLocation.lon],11);status.textContent="Standort gefunden.";render()},()=>status.textContent="Standortfreigabe wurde abgelehnt oder konnte nicht ermittelt werden.",{enableHighAccuracy:true,timeout:15000,maximumAge:60000})}
function showById(id){const p=places.find(x=>x.id===id);if(p){p.distance=userLocation?dist(userLocation.lat,userLocation.lon,p.lat,p.lon):null;show(p)}}
function show(p){document.getElementById("modalContent").innerHTML=`<h2>🏖️ ${esc(p.name)}</h2><p>${esc(p.description)}</p>${p.distance==null?"":`<p><b>Entfernung:</b> ${p.distance.toFixed(1)} km</p>`}<p><b>Status:</b> ${esc(p.type)}</p><a class="route" target="_blank" href="https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lon}">🧭 Route öffnen</a>`;document.getElementById("modal").classList.remove("hidden")}
map=L.map("map").setView([52.62,10.08],10);L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap-Mitwirkende"}).addTo(map);render();
radius.oninput=()=>{radiusValue.textContent=radius.value+" km";render()};document.getElementById("locationBtn").onclick=locate;document.getElementById("locateBtn").onclick=locate;document.getElementById("closeModal").onclick=()=>document.getElementById("modal").classList.add("hidden");document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")e.target.classList.add("hidden")};